package org.opensrp.stock.openlmis.domain;

public class Lot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.id
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.lot_code
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private String lotCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.expiration_date
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private Long expirationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.manufucture_date
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private Long manufuctureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.trade_item_id
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private String tradeItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.active
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.server_version
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private Long serverVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.lot.date_deleted
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    private Long dateDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.id
     *
     * @return the value of core.lot.id
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.id
     *
     * @param id the value for core.lot.id
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.lot_code
     *
     * @return the value of core.lot.lot_code
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public String getLotCode() {
        return lotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.lot_code
     *
     * @param lotCode the value for core.lot.lot_code
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setLotCode(String lotCode) {
        this.lotCode = lotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.expiration_date
     *
     * @return the value of core.lot.expiration_date
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Long getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.expiration_date
     *
     * @param expirationDate the value for core.lot.expiration_date
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setExpirationDate(Long expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.manufucture_date
     *
     * @return the value of core.lot.manufucture_date
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Long getManufuctureDate() {
        return manufuctureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.manufucture_date
     *
     * @param manufuctureDate the value for core.lot.manufucture_date
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setManufuctureDate(Long manufuctureDate) {
        this.manufuctureDate = manufuctureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.trade_item_id
     *
     * @return the value of core.lot.trade_item_id
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public String getTradeItemId() {
        return tradeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.trade_item_id
     *
     * @param tradeItemId the value for core.lot.trade_item_id
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setTradeItemId(String tradeItemId) {
        this.tradeItemId = tradeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.active
     *
     * @return the value of core.lot.active
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.active
     *
     * @param active the value for core.lot.active
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.server_version
     *
     * @return the value of core.lot.server_version
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Long getServerVersion() {
        return serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.server_version
     *
     * @param serverVersion the value for core.lot.server_version
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setServerVersion(Long serverVersion) {
        this.serverVersion = serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.lot.date_deleted
     *
     * @return the value of core.lot.date_deleted
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Long getDateDeleted() {
        return dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.lot.date_deleted
     *
     * @param dateDeleted the value for core.lot.date_deleted
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setDateDeleted(Long dateDeleted) {
        this.dateDeleted = dateDeleted;
    }
}