package org.opensrp.stock.openlmis.domain;

import org.opensrp.stock.openlmis.exception.NullQueryValueException;

import java.util.ArrayList;
import java.util.List;

public class LotExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public LotExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new NullQueryValueException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new NullQueryValueException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new NullQueryValueException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLotCodeIsNull() {
            addCriterion("lot_code is null");
            return (Criteria) this;
        }

        public Criteria andLotCodeIsNotNull() {
            addCriterion("lot_code is not null");
            return (Criteria) this;
        }

        public Criteria andLotCodeEqualTo(String value) {
            addCriterion("lot_code =", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeNotEqualTo(String value) {
            addCriterion("lot_code <>", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeGreaterThan(String value) {
            addCriterion("lot_code >", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeGreaterThanOrEqualTo(String value) {
            addCriterion("lot_code >=", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeLessThan(String value) {
            addCriterion("lot_code <", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeLessThanOrEqualTo(String value) {
            addCriterion("lot_code <=", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeLike(String value) {
            addCriterion("lot_code like", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeNotLike(String value) {
            addCriterion("lot_code not like", value, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeIn(List<String> values) {
            addCriterion("lot_code in", values, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeNotIn(List<String> values) {
            addCriterion("lot_code not in", values, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeBetween(String value1, String value2) {
            addCriterion("lot_code between", value1, value2, "lotCode");
            return (Criteria) this;
        }

        public Criteria andLotCodeNotBetween(String value1, String value2) {
            addCriterion("lot_code not between", value1, value2, "lotCode");
            return (Criteria) this;
        }

        public Criteria andExpirationDateIsNull() {
            addCriterion("expiration_date is null");
            return (Criteria) this;
        }

        public Criteria andExpirationDateIsNotNull() {
            addCriterion("expiration_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpirationDateEqualTo(Long value) {
            addCriterion("expiration_date =", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateNotEqualTo(Long value) {
            addCriterion("expiration_date <>", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateGreaterThan(Long value) {
            addCriterion("expiration_date >", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateGreaterThanOrEqualTo(Long value) {
            addCriterion("expiration_date >=", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateLessThan(Long value) {
            addCriterion("expiration_date <", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateLessThanOrEqualTo(Long value) {
            addCriterion("expiration_date <=", value, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateIn(List<Long> values) {
            addCriterion("expiration_date in", values, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateNotIn(List<Long> values) {
            addCriterion("expiration_date not in", values, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateBetween(Long value1, Long value2) {
            addCriterion("expiration_date between", value1, value2, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andExpirationDateNotBetween(Long value1, Long value2) {
            addCriterion("expiration_date not between", value1, value2, "expirationDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateIsNull() {
            addCriterion("manufucture_date is null");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateIsNotNull() {
            addCriterion("manufucture_date is not null");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateEqualTo(Long value) {
            addCriterion("manufucture_date =", value, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateNotEqualTo(Long value) {
            addCriterion("manufucture_date <>", value, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateGreaterThan(Long value) {
            addCriterion("manufucture_date >", value, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateGreaterThanOrEqualTo(Long value) {
            addCriterion("manufucture_date >=", value, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateLessThan(Long value) {
            addCriterion("manufucture_date <", value, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateLessThanOrEqualTo(Long value) {
            addCriterion("manufucture_date <=", value, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateIn(List<Long> values) {
            addCriterion("manufucture_date in", values, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateNotIn(List<Long> values) {
            addCriterion("manufucture_date not in", values, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateBetween(Long value1, Long value2) {
            addCriterion("manufucture_date between", value1, value2, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andManufuctureDateNotBetween(Long value1, Long value2) {
            addCriterion("manufucture_date not between", value1, value2, "manufuctureDate");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdIsNull() {
            addCriterion("trade_item_id is null");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdIsNotNull() {
            addCriterion("trade_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdEqualTo(String value) {
            addCriterion("trade_item_id =", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotEqualTo(String value) {
            addCriterion("trade_item_id <>", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdGreaterThan(String value) {
            addCriterion("trade_item_id >", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("trade_item_id >=", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdLessThan(String value) {
            addCriterion("trade_item_id <", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdLessThanOrEqualTo(String value) {
            addCriterion("trade_item_id <=", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdLike(String value) {
            addCriterion("trade_item_id like", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotLike(String value) {
            addCriterion("trade_item_id not like", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdIn(List<String> values) {
            addCriterion("trade_item_id in", values, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotIn(List<String> values) {
            addCriterion("trade_item_id not in", values, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdBetween(String value1, String value2) {
            addCriterion("trade_item_id between", value1, value2, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotBetween(String value1, String value2) {
            addCriterion("trade_item_id not between", value1, value2, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("active is null");
            return (Criteria) this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("active is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEqualTo(Boolean value) {
            addCriterion("active =", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotEqualTo(Boolean value) {
            addCriterion("active <>", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThan(Boolean value) {
            addCriterion("active >", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("active >=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThan(Boolean value) {
            addCriterion("active <", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("active <=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveIn(List<Boolean> values) {
            addCriterion("active in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotIn(List<Boolean> values) {
            addCriterion("active not in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("active between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("active not between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andServerVersionIsNull() {
            addCriterion("server_version is null");
            return (Criteria) this;
        }

        public Criteria andServerVersionIsNotNull() {
            addCriterion("server_version is not null");
            return (Criteria) this;
        }

        public Criteria andServerVersionEqualTo(Long value) {
            addCriterion("server_version =", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionNotEqualTo(Long value) {
            addCriterion("server_version <>", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionGreaterThan(Long value) {
            addCriterion("server_version >", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("server_version >=", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionLessThan(Long value) {
            addCriterion("server_version <", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionLessThanOrEqualTo(Long value) {
            addCriterion("server_version <=", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionIn(List<Long> values) {
            addCriterion("server_version in", values, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionNotIn(List<Long> values) {
            addCriterion("server_version not in", values, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionBetween(Long value1, Long value2) {
            addCriterion("server_version between", value1, value2, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionNotBetween(Long value1, Long value2) {
            addCriterion("server_version not between", value1, value2, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIsNull() {
            addCriterion("date_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIsNotNull() {
            addCriterion("date_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDateDeletedEqualTo(Long value) {
            addCriterion("date_deleted =", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotEqualTo(Long value) {
            addCriterion("date_deleted <>", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedGreaterThan(Long value) {
            addCriterion("date_deleted >", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedGreaterThanOrEqualTo(Long value) {
            addCriterion("date_deleted >=", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedLessThan(Long value) {
            addCriterion("date_deleted <", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedLessThanOrEqualTo(Long value) {
            addCriterion("date_deleted <=", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIn(List<Long> values) {
            addCriterion("date_deleted in", values, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotIn(List<Long> values) {
            addCriterion("date_deleted not in", values, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedBetween(Long value1, Long value2) {
            addCriterion("date_deleted between", value1, value2, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotBetween(Long value1, Long value2) {
            addCriterion("date_deleted not between", value1, value2, "dateDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.lot
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 03 13:19:08 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.lot
     *
     * @mbg.generated Fri Aug 03 13:19:08 EAT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}