package org.opensrp.stock.openlmis.domain;

import java.util.ArrayList;
import java.util.List;

public class MasterMetadataEntryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public MasterMetadataEntryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdIsNull() {
            addCriterion("master_table_entry_id is null");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdIsNotNull() {
            addCriterion("master_table_entry_id is not null");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdEqualTo(Long value) {
            addCriterion("master_table_entry_id =", value, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdNotEqualTo(Long value) {
            addCriterion("master_table_entry_id <>", value, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdGreaterThan(Long value) {
            addCriterion("master_table_entry_id >", value, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("master_table_entry_id >=", value, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdLessThan(Long value) {
            addCriterion("master_table_entry_id <", value, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdLessThanOrEqualTo(Long value) {
            addCriterion("master_table_entry_id <=", value, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdIn(List<Long> values) {
            addCriterion("master_table_entry_id in", values, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdNotIn(List<Long> values) {
            addCriterion("master_table_entry_id not in", values, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdBetween(Long value1, Long value2) {
            addCriterion("master_table_entry_id between", value1, value2, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andMasterTableEntryIdNotBetween(Long value1, Long value2) {
            addCriterion("master_table_entry_id not between", value1, value2, "masterTableEntryId");
            return (Criteria) this;
        }

        public Criteria andServerVersionIsNull() {
            addCriterion("server_version is null");
            return (Criteria) this;
        }

        public Criteria andServerVersionIsNotNull() {
            addCriterion("server_version is not null");
            return (Criteria) this;
        }

        public Criteria andServerVersionEqualTo(Long value) {
            addCriterion("server_version =", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionNotEqualTo(Long value) {
            addCriterion("server_version <>", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionGreaterThan(Long value) {
            addCriterion("server_version >", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("server_version >=", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionLessThan(Long value) {
            addCriterion("server_version <", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionLessThanOrEqualTo(Long value) {
            addCriterion("server_version <=", value, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionIn(List<Long> values) {
            addCriterion("server_version in", values, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionNotIn(List<Long> values) {
            addCriterion("server_version not in", values, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionBetween(Long value1, Long value2) {
            addCriterion("server_version between", value1, value2, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andServerVersionNotBetween(Long value1, Long value2) {
            addCriterion("server_version not between", value1, value2, "serverVersion");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIsNull() {
            addCriterion("date_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIsNotNull() {
            addCriterion("date_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDateDeletedEqualTo(Long value) {
            addCriterion("date_deleted =", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotEqualTo(Long value) {
            addCriterion("date_deleted <>", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedGreaterThan(Long value) {
            addCriterion("date_deleted >", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedGreaterThanOrEqualTo(Long value) {
            addCriterion("date_deleted >=", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedLessThan(Long value) {
            addCriterion("date_deleted <", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedLessThanOrEqualTo(Long value) {
            addCriterion("date_deleted <=", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIn(List<Long> values) {
            addCriterion("date_deleted in", values, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotIn(List<Long> values) {
            addCriterion("date_deleted not in", values, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedBetween(Long value1, Long value2) {
            addCriterion("date_deleted between", value1, value2, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotBetween(Long value1, Long value2) {
            addCriterion("date_deleted not between", value1, value2, "dateDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.master_metadata
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 25 16:08:22 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.master_metadata
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}