package org.opensrp.stock.openlmis.domain.postgres;

public class MasterMetadataEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.master_metadata.id
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.master_metadata.uuid
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.master_metadata.type
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.master_metadata.master_table_entry_id
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    private Long masterTableEntryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.master_metadata.server_version
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    private Long serverVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.master_metadata.date_deleted
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    private Long dateDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.master_metadata.id
     *
     * @return the value of core.master_metadata.id
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.master_metadata.id
     *
     * @param id the value for core.master_metadata.id
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.master_metadata.uuid
     *
     * @return the value of core.master_metadata.uuid
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.master_metadata.uuid
     *
     * @param uuid the value for core.master_metadata.uuid
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.master_metadata.type
     *
     * @return the value of core.master_metadata.type
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.master_metadata.type
     *
     * @param type the value for core.master_metadata.type
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.master_metadata.master_table_entry_id
     *
     * @return the value of core.master_metadata.master_table_entry_id
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public Long getMasterTableEntryId() {
        return masterTableEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.master_metadata.master_table_entry_id
     *
     * @param masterTableEntryId the value for core.master_metadata.master_table_entry_id
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public void setMasterTableEntryId(Long masterTableEntryId) {
        this.masterTableEntryId = masterTableEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.master_metadata.server_version
     *
     * @return the value of core.master_metadata.server_version
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public Long getServerVersion() {
        return serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.master_metadata.server_version
     *
     * @param serverVersion the value for core.master_metadata.server_version
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public void setServerVersion(Long serverVersion) {
        this.serverVersion = serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.master_metadata.date_deleted
     *
     * @return the value of core.master_metadata.date_deleted
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public Long getDateDeleted() {
        return dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.master_metadata.date_deleted
     *
     * @param dateDeleted the value for core.master_metadata.date_deleted
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    public void setDateDeleted(Long dateDeleted) {
        this.dateDeleted = dateDeleted;
    }
}