package org.opensrp.stock.openlmis.domain.postgres;

import java.util.ArrayList;
import java.util.List;

public class OrderableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public OrderableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeIsNull() {
            addCriterion("full_product_code is null");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeIsNotNull() {
            addCriterion("full_product_code is not null");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeEqualTo(String value) {
            addCriterion("full_product_code =", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeNotEqualTo(String value) {
            addCriterion("full_product_code <>", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeGreaterThan(String value) {
            addCriterion("full_product_code >", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("full_product_code >=", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeLessThan(String value) {
            addCriterion("full_product_code <", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeLessThanOrEqualTo(String value) {
            addCriterion("full_product_code <=", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeLike(String value) {
            addCriterion("full_product_code like", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeNotLike(String value) {
            addCriterion("full_product_code not like", value, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeIn(List<String> values) {
            addCriterion("full_product_code in", values, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeNotIn(List<String> values) {
            addCriterion("full_product_code not in", values, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeBetween(String value1, String value2) {
            addCriterion("full_product_code between", value1, value2, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andFullProductCodeNotBetween(String value1, String value2) {
            addCriterion("full_product_code not between", value1, value2, "fullProductCode");
            return (Criteria) this;
        }

        public Criteria andNetContentIsNull() {
            addCriterion("net_content is null");
            return (Criteria) this;
        }

        public Criteria andNetContentIsNotNull() {
            addCriterion("net_content is not null");
            return (Criteria) this;
        }

        public Criteria andNetContentEqualTo(Integer value) {
            addCriterion("net_content =", value, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentNotEqualTo(Integer value) {
            addCriterion("net_content <>", value, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentGreaterThan(Integer value) {
            addCriterion("net_content >", value, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentGreaterThanOrEqualTo(Integer value) {
            addCriterion("net_content >=", value, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentLessThan(Integer value) {
            addCriterion("net_content <", value, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentLessThanOrEqualTo(Integer value) {
            addCriterion("net_content <=", value, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentIn(List<Integer> values) {
            addCriterion("net_content in", values, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentNotIn(List<Integer> values) {
            addCriterion("net_content not in", values, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentBetween(Integer value1, Integer value2) {
            addCriterion("net_content between", value1, value2, "netContent");
            return (Criteria) this;
        }

        public Criteria andNetContentNotBetween(Integer value1, Integer value2) {
            addCriterion("net_content not between", value1, value2, "netContent");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdIsNull() {
            addCriterion("pack_rounding_threshold is null");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdIsNotNull() {
            addCriterion("pack_rounding_threshold is not null");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdEqualTo(Integer value) {
            addCriterion("pack_rounding_threshold =", value, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdNotEqualTo(Integer value) {
            addCriterion("pack_rounding_threshold <>", value, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdGreaterThan(Integer value) {
            addCriterion("pack_rounding_threshold >", value, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pack_rounding_threshold >=", value, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdLessThan(Integer value) {
            addCriterion("pack_rounding_threshold <", value, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdLessThanOrEqualTo(Integer value) {
            addCriterion("pack_rounding_threshold <=", value, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdIn(List<Integer> values) {
            addCriterion("pack_rounding_threshold in", values, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdNotIn(List<Integer> values) {
            addCriterion("pack_rounding_threshold not in", values, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdBetween(Integer value1, Integer value2) {
            addCriterion("pack_rounding_threshold between", value1, value2, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andPackRoundingThresholdNotBetween(Integer value1, Integer value2) {
            addCriterion("pack_rounding_threshold not between", value1, value2, "packRoundingThreshold");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroIsNull() {
            addCriterion("round_to_zero is null");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroIsNotNull() {
            addCriterion("round_to_zero is not null");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroEqualTo(Boolean value) {
            addCriterion("round_to_zero =", value, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroNotEqualTo(Boolean value) {
            addCriterion("round_to_zero <>", value, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroGreaterThan(Boolean value) {
            addCriterion("round_to_zero >", value, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroGreaterThanOrEqualTo(Boolean value) {
            addCriterion("round_to_zero >=", value, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroLessThan(Boolean value) {
            addCriterion("round_to_zero <", value, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroLessThanOrEqualTo(Boolean value) {
            addCriterion("round_to_zero <=", value, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroIn(List<Boolean> values) {
            addCriterion("round_to_zero in", values, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroNotIn(List<Boolean> values) {
            addCriterion("round_to_zero not in", values, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroBetween(Boolean value1, Boolean value2) {
            addCriterion("round_to_zero between", value1, value2, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andRoundToZeroNotBetween(Boolean value1, Boolean value2) {
            addCriterion("round_to_zero not between", value1, value2, "roundToZero");
            return (Criteria) this;
        }

        public Criteria andDispensableIsNull() {
            addCriterion("dispensable is null");
            return (Criteria) this;
        }

        public Criteria andDispensableIsNotNull() {
            addCriterion("dispensable is not null");
            return (Criteria) this;
        }

        public Criteria andDispensableEqualTo(Integer value) {
            addCriterion("dispensable =", value, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableNotEqualTo(Integer value) {
            addCriterion("dispensable <>", value, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableGreaterThan(Integer value) {
            addCriterion("dispensable >", value, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableGreaterThanOrEqualTo(Integer value) {
            addCriterion("dispensable >=", value, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableLessThan(Integer value) {
            addCriterion("dispensable <", value, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableLessThanOrEqualTo(Integer value) {
            addCriterion("dispensable <=", value, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableIn(List<Integer> values) {
            addCriterion("dispensable in", values, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableNotIn(List<Integer> values) {
            addCriterion("dispensable not in", values, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableBetween(Integer value1, Integer value2) {
            addCriterion("dispensable between", value1, value2, "dispensable");
            return (Criteria) this;
        }

        public Criteria andDispensableNotBetween(Integer value1, Integer value2) {
            addCriterion("dispensable not between", value1, value2, "dispensable");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdIsNull() {
            addCriterion("trade_item_id is null");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdIsNotNull() {
            addCriterion("trade_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdEqualTo(String value) {
            addCriterion("trade_item_id =", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotEqualTo(String value) {
            addCriterion("trade_item_id <>", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdGreaterThan(String value) {
            addCriterion("trade_item_id >", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("trade_item_id >=", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdLessThan(String value) {
            addCriterion("trade_item_id <", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdLessThanOrEqualTo(String value) {
            addCriterion("trade_item_id <=", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdLike(String value) {
            addCriterion("trade_item_id like", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotLike(String value) {
            addCriterion("trade_item_id not like", value, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdIn(List<String> values) {
            addCriterion("trade_item_id in", values, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotIn(List<String> values) {
            addCriterion("trade_item_id not in", values, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdBetween(String value1, String value2) {
            addCriterion("trade_item_id between", value1, value2, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andTradeItemIdNotBetween(String value1, String value2) {
            addCriterion("trade_item_id not between", value1, value2, "tradeItemId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdIsNull() {
            addCriterion("commodity_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdIsNotNull() {
            addCriterion("commodity_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdEqualTo(String value) {
            addCriterion("commodity_type_id =", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdNotEqualTo(String value) {
            addCriterion("commodity_type_id <>", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdGreaterThan(String value) {
            addCriterion("commodity_type_id >", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_type_id >=", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdLessThan(String value) {
            addCriterion("commodity_type_id <", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdLessThanOrEqualTo(String value) {
            addCriterion("commodity_type_id <=", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdLike(String value) {
            addCriterion("commodity_type_id like", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdNotLike(String value) {
            addCriterion("commodity_type_id not like", value, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdIn(List<String> values) {
            addCriterion("commodity_type_id in", values, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdNotIn(List<String> values) {
            addCriterion("commodity_type_id not in", values, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdBetween(String value1, String value2) {
            addCriterion("commodity_type_id between", value1, value2, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIdNotBetween(String value1, String value2) {
            addCriterion("commodity_type_id not between", value1, value2, "commodityTypeId");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIsNull() {
            addCriterion("date_updated is null");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIsNotNull() {
            addCriterion("date_updated is not null");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedEqualTo(Long value) {
            addCriterion("date_updated =", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotEqualTo(Long value) {
            addCriterion("date_updated <>", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedGreaterThan(Long value) {
            addCriterion("date_updated >", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedGreaterThanOrEqualTo(Long value) {
            addCriterion("date_updated >=", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedLessThan(Long value) {
            addCriterion("date_updated <", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedLessThanOrEqualTo(Long value) {
            addCriterion("date_updated <=", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIn(List<Long> values) {
            addCriterion("date_updated in", values, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotIn(List<Long> values) {
            addCriterion("date_updated not in", values, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedBetween(Long value1, Long value2) {
            addCriterion("date_updated between", value1, value2, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotBetween(Long value1, Long value2) {
            addCriterion("date_updated not between", value1, value2, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIsNull() {
            addCriterion("date_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIsNotNull() {
            addCriterion("date_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDateDeletedEqualTo(Long value) {
            addCriterion("date_deleted =", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotEqualTo(Long value) {
            addCriterion("date_deleted <>", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedGreaterThan(Long value) {
            addCriterion("date_deleted >", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedGreaterThanOrEqualTo(Long value) {
            addCriterion("date_deleted >=", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedLessThan(Long value) {
            addCriterion("date_deleted <", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedLessThanOrEqualTo(Long value) {
            addCriterion("date_deleted <=", value, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedIn(List<Long> values) {
            addCriterion("date_deleted in", values, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotIn(List<Long> values) {
            addCriterion("date_deleted not in", values, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedBetween(Long value1, Long value2) {
            addCriterion("date_deleted between", value1, value2, "dateDeleted");
            return (Criteria) this;
        }

        public Criteria andDateDeletedNotBetween(Long value1, Long value2) {
            addCriterion("date_deleted not between", value1, value2, "dateDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.orderable
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 16:09:35 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.orderable
     *
     * @mbg.generated Thu Jul 12 16:09:35 EAT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}