package org.opensrp.stock.openlmis.domain.postgres;

public class ProgramOrderable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.program_id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private String programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.orderable_id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private String orderableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.doses_per_patient
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private Integer dosesPerPatient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.active
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.full_supply
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private Boolean fullSupply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.date_updated
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private Long dateUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.program_orderable.date_deleted
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    private Long dateDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.id
     *
     * @return the value of core.program_orderable.id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.id
     *
     * @param id the value for core.program_orderable.id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.program_id
     *
     * @return the value of core.program_orderable.program_id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.program_id
     *
     * @param programId the value for core.program_orderable.program_id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setProgramId(String programId) {
        this.programId = programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.orderable_id
     *
     * @return the value of core.program_orderable.orderable_id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public String getOrderableId() {
        return orderableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.orderable_id
     *
     * @param orderableId the value for core.program_orderable.orderable_id
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setOrderableId(String orderableId) {
        this.orderableId = orderableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.doses_per_patient
     *
     * @return the value of core.program_orderable.doses_per_patient
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public Integer getDosesPerPatient() {
        return dosesPerPatient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.doses_per_patient
     *
     * @param dosesPerPatient the value for core.program_orderable.doses_per_patient
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setDosesPerPatient(Integer dosesPerPatient) {
        this.dosesPerPatient = dosesPerPatient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.active
     *
     * @return the value of core.program_orderable.active
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.active
     *
     * @param active the value for core.program_orderable.active
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.full_supply
     *
     * @return the value of core.program_orderable.full_supply
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public Boolean getFullSupply() {
        return fullSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.full_supply
     *
     * @param fullSupply the value for core.program_orderable.full_supply
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setFullSupply(Boolean fullSupply) {
        this.fullSupply = fullSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.date_updated
     *
     * @return the value of core.program_orderable.date_updated
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public Long getDateUpdated() {
        return dateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.date_updated
     *
     * @param dateUpdated the value for core.program_orderable.date_updated
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setDateUpdated(Long dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.program_orderable.date_deleted
     *
     * @return the value of core.program_orderable.date_deleted
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public Long getDateDeleted() {
        return dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.program_orderable.date_deleted
     *
     * @param dateDeleted the value for core.program_orderable.date_deleted
     *
     * @mbg.generated Fri Jul 13 11:37:43 EAT 2018
     */
    public void setDateDeleted(Long dateDeleted) {
        this.dateDeleted = dateDeleted;
    }
}