package org.opensrp.stock.openlmis.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.stock.openlmis.domain.Orderable;
import org.opensrp.stock.openlmis.domain.OrderableExample;

public interface OrderableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    long countByExample(OrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int deleteByExample(OrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int insert(Orderable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int insertSelective(Orderable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    List<Orderable> selectByExample(OrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    Orderable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByExampleSelective(@Param("record") Orderable record, @Param("example") OrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByExample(@Param("record") Orderable record, @Param("example") OrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByPrimaryKeySelective(Orderable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByPrimaryKey(Orderable record);
}