package org.opensrp.stock.openlmis.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.stock.openlmis.domain.ProgramOrderable;
import org.opensrp.stock.openlmis.domain.ProgramOrderableExample;

public interface ProgramOrderableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    long countByExample(ProgramOrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int deleteByExample(ProgramOrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int insert(ProgramOrderable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int insertSelective(ProgramOrderable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    List<ProgramOrderable> selectByExample(ProgramOrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    ProgramOrderable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByExampleSelective(@Param("record") ProgramOrderable record, @Param("example") ProgramOrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByExample(@Param("record") ProgramOrderable record, @Param("example") ProgramOrderableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByPrimaryKeySelective(ProgramOrderable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.program_orderable
     *
     * @mbg.generated Wed Jul 25 16:08:22 EAT 2018
     */
    int updateByPrimaryKey(ProgramOrderable record);
}