package org.opensrp.stock.openlmis.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.stock.openlmis.domain.postgres.MasterMetadataEntry;
import org.opensrp.stock.openlmis.domain.postgres.MasterMetadataEntryExample;

public interface MasterMetadataEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    long countByExample(MasterMetadataEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int deleteByExample(MasterMetadataEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int insert(MasterMetadataEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int insertSelective(MasterMetadataEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    List<MasterMetadataEntry> selectByExample(MasterMetadataEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    MasterMetadataEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int updateByExampleSelective(@Param("record") MasterMetadataEntry record, @Param("example") MasterMetadataEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int updateByExample(@Param("record") MasterMetadataEntry record, @Param("example") MasterMetadataEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int updateByPrimaryKeySelective(MasterMetadataEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.master_metadata
     *
     * @mbg.generated Thu Jul 19 17:04:56 EAT 2018
     */
    int updateByPrimaryKey(MasterMetadataEntry record);
}